{% set name = "funcargparse" %}
{% set version = "0.2.1" %}
{% set sha256 = "2e854ee568938f287477b2e27d78708dcb74417869840b1bff36992fd5ab0a4e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - docrep
    - six

test:
  imports:
    - funcargparse

about:
  home: https://github.com/Chilipp/funcargparse
  license: GPL-2.0
  license_family: GPL2
  license_file: LICENSE
  summary: 'Create an argparse.ArgumentParser from function docstrings'

  description: |
    The funcargparse module allows you to create an argparse.ArgumentParser
    including the help directly from a function
  doc_url: http://funcargparse.readthedocs.io/
  dev_url: https://github.com/Chilipp/funcargparse

extra:
  recipe-maintainers:
    - Chilipp
