{% set name = "funcargparse" %}
{% set version = "0.2.0" %}
{% set sha256 = "a99c3d42faef39393e21cfe0916a9294d7d1d7514e22110182ce4e42685b376d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - docrep >=0.2.2
    - six

test:
  imports:
    - funcargparse

about:
  home: https://github.com/Chilipp/funcargparse
  license: GPL-2.0
  license_family: GPL2
  license_file: LICENSE
  summary: 'Create an argparse.ArgumentParser from function docstrings'

  description: |
    The funcargparse module allows you to create an argparse.ArgumentParser
    including the help directly from a function
  doc_url: http://funcargparse.readthedocs.io/
  dev_url: https://github.com/Chilipp/funcargparse

extra:
  recipe-maintainers:
    - Chilipp
