{% set name = "funcargparse" %}
{% set version = "0.2.4" %}
{% set sha256 = "d9183a7ac62c8ab766faa24ed380a1d38b368e8563863899d64cc54a6463e0cd" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - python >=3.6
    - docrep >=0.3
    - six

test:
  imports:
    - funcargparse

about:
  home: https://github.com/Chilipp/funcargparse
  license: Apache-2.0
  license_file: LICENSE
  summary: Create an argparse.ArgumentParser from function docstrings

  description: |
    The funcargparse module allows you to create an argparse.ArgumentParser
    including the help directly from a function
  doc_url: http://funcargparse.readthedocs.io/
  dev_url: https://github.com/Chilipp/funcargparse

extra:
  recipe-maintainers:
    - Chilipp
