travis:
  secure:
    BINSTAR_TOKEN: 30nOI0YOPqNnd0rdAR2/dIfxbPsdML4nnUSVUBolHGg2fGfO82AIH6vfh4NHbQMzj/rHA1khL83vyLT5ddOyeEeIIvUHbkkzyu64nHpozzGeC580cXdJXwY4Vmy2on6hZ3H20NWEOh+Bg00Q++6uld6+ROiLPkGmgmwlXoFl4meGht6iu1FU5lyUydbUIxiyqwtOmNKVsO8Ub3XcuExr6d/lb/E3lkfzwBbs5U8A1wTTlhm5R9XPJmXQpbYwrppCPqI67LW7pmWqqaBYNteWkUqDiF9GdO4/nvCmpc+chSMKUDlGufv/nXMTr7AarWCZU0kpJ1RxsakgQjs90oIpzQLwBC8uGPPGl6uFnibJeG5GtAlH3gq+4FQRazDpv0H7smSTOJXjYsXxW5h9aTmKVW3GB3kK/+l6lYisGTFqo0ppkwnpD42iUQen0ssqqCsnPL4yIuAkgiP/2fKCCR1hLntlSWXa/p0itHgD4I4x/5IHrKDpM1HD43yN7HbrcBAXyy4jkBcTQugia/uo53TiPMx4QSJ3Vp90OqbX/mV1kf5shn660eTAjMtWjXQys0hv+h1cgh5YvaDSGUaVodbeAcm/7KE0X7rQJoT3sDYKTB8ji26XaXIkTYHiOMpzOJrrvZJkbDrmwV9M0SU/T/byvW/zhO80SQYLC1kTk06JlEo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
