travis:
  secure:
    BINSTAR_TOKEN: E/CJ/x3VYWf1jI0eOe0nEumfBeCmBEkca0890S1Brhj4Z67TvzlzlMOdpYL9JwLBHroDm3uARCB9cuo3JV/C8K8ZsMYReriKEYztVvvklrqJmx4M2YJ4ez+GX78BI0QvAxlTmSQq/p3c/XbkRhEXUneTd4BeS6gFTQkeQ7qlfyAkg4HVip263sluMsBHuSh63KguDlVzb93Uu5aFv6yI3tCQpq0UfjzumIMIAS1ZFH4xAuq7T9WpYWCS1ikmqMj5AU99CnkbWCE92BG3yjdPia2jZeooHIAhcYaWdCPfjHi7zsU84UA+M8mh9eqY8sgNh0TxglVtbMKv2YK7xIbGjHkmBlSq75sN2D73W5s2IWBROvarraKlpu5j76UeY1yUPZLFoHkHBtTOCrk27h4ts+FAxaSYeT67cV4MPvEAGmOusHHm8PFQmLEmYycIcVHVW9K+nPkNHpJSRXgY19zLUwo3AFqdXuMOui1gTZXdf+mWIuhd99ojSnBhVdrEhOzk2LOTjL1L7d6sHJmYpGxS9DWd+SNm1v4+GNoME3DiZFmcBSfJANjFkpf3hu2Lf4WjNJhznS1KysFAAagu9Xge0DFiRtmOLE9bMdU7bOVGgc/N8/fFmhq2BZcbBsG27L7WIYefanojlnwQg9FUdK3Z6DsMjrg9oUDPOYlc63SvHts=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
